# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-30 19:45:34
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def CostSurfaceRasterCreationTool(DEM_Input, Contour_interval=100, Reclassification="0 6;24 0;48 1;96 2;192 3;384 4;768 5;NODATA 6", Distances=[24, 48, 96, 192, 384, 768], Surface_Cost_Raster="C:\\Users\\Katherine Gates\\Dropbox\\KeystoneFall2024\\KeystoneData\\Model Creation and SR tool\\Model Creation and SR tool.gdb\\Reclass_Rast1"):  # CostSurfaceRasterCreationTool

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\users\katherine gates\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\Analysis Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(cellSize="MAXOF", mask="dem_clip"):
        Contour_Input = ""

        # Process: Create Contour (Contour) (sa)
        Contour_Output = ""
        with arcpy.EnvManager(outputCoordinateSystem="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]"):
            arcpy.sa.Contour(DEM_Input.__str__().format(**locals(),**globals())if isinstance(DEM_Input, str) else DEM_Input, Contour_Output, Contour_interval.__str__().format(**locals(),**globals())if isinstance(Contour_interval, str) else Contour_interval, 0, 1, "CONTOUR", None)
            .save(Create_Contour)


        # Process: Multiple Ring Buffer (Multiple Ring Buffer) (analysis)
        MultipleRingBuffer_Output = ""
        arcpy.analysis.MultipleRingBuffer(Input_Features=Contour_Output, Output_Feature_class=MultipleRingBuffer_Output, Distances=Distances.__str__().format(**locals(),**globals())if isinstance(Distances, str) else Distances, Buffer_Unit="Meters", Field_Name="distance", Dissolve_Option="ALL", Outside_Polygons_Only="FULL", Method="GEODESIC")

        # Process: Feature to Raster (Feature to Raster) (conversion)
        FeatureToRaster_Output = ""
        arcpy.conversion.FeatureToRaster(in_features=MultipleRingBuffer_Output, field="", out_raster=FeatureToRaster_Output, cell_size=DEM_Input.__str__().format(**locals(),**globals())if isinstance(DEM_Input, str) else DEM_Input)
        FeatureToRaster_Output = arcpy.Raster(FeatureToRaster_Output)

        # Process: Raster Calculator (Raster Calculator) (sa)
        RasterCalc_Output = "C:\\Users\\Katherine Gates\\Dropbox\\KeystoneFall2024\\KeystoneData\\Model Creation and SR tool\\Model Creation and SR tool.gdb\\RasterC_2"
        Raster_Calculator = RasterCalc_Output
        with arcpy.EnvManager(cellSize="MAXOF"):
            RasterCalc_Output = Con(IsNull(FeatureToRaster_Output), 0, FeatureToRaster_Output)
            RasterCalc_Output.save(Raster_Calculator)


        # Process: Reclassify (Reclassify) (sa)
        Reclassify = Surface_Cost_Raster
        Surface_Cost_Raster = arcpy.sa.Reclassify(RasterCalc_Output, "Value", Reclassification.__str__().format(**locals(),**globals())if isinstance(Reclassification, str) else Reclassification, "DATA")
        Surface_Cost_Raster.save(Reclassify)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", compression="LZ77", 
                          maintainAttachments=True, maintainSpatialIndex=False, matchMultidimensionalVariable=True, 
                          nodata="NONE", outputMFlag="Same As Input", outputZFlag="Same As Input", 
                          preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", qualifiedFieldNames=True, 
                          randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", resamplingMethod="NEAREST", 
                          scratchWorkspace="C:\\Users\\Katherine Gates\\Dropbox\\KeystoneFall2024\\KeystoneData\\Model Creation and SR tool\\Model Creation and SR tool.gdb", terrainMemoryUsage=False, tileSize="128 128", 
                          tinSaveVersion="CURRENT", transferDomains=False, transferGDBAttributeProperties=False, 
                          unionDimension=False, workspace="C:\\Users\\Katherine Gates\\Dropbox\\KeystoneFall2024\\KeystoneData\\Model Creation and SR tool\\Model Creation and SR tool.gdb"):
        CostSurfaceRasterCreationTool(*argv[1:])
